piece_index:
    path:     /
    defaults: { _controller: "MultiServiceGsmPieceBundle:Piece:index" }
    methods:  GET

piece_show:
    path:     /{id}/show
    defaults: { _controller: "MultiServiceGsmPieceBundle:Piece:show" }
    methods:  GET

piece_new:
    path:     /new
    defaults: { _controller: "MultiServiceGsmPieceBundle:Piece:new" }
    methods:  [GET, POST]

piece_edit:
    path:     /{id}/edit
    defaults: { _controller: "MultiServiceGsmPieceBundle:Piece:edit" }
    methods:  [GET, POST]

piece_delete:
    path:     /{id}/delete
    defaults: { _controller: "MultiServiceGsmPieceBundle:Piece:delete" }
    methods:  DELETE

piece_supprimIndiv:
    path:   /{id}/deleteIndiv
    defaults : { _controller: "MultiServiceGsmPiecesBundle:Piece:deleteIndiv" }
    methods: DELETE
