multi_service_gsm_pieces_piece:
    resource: "@MultiServiceGsmPiecesBundle/Resources/config/routing/piece.yml"
    prefix:   /piece

multi_service_gsm_pieces_homepage:
    path:     /
    defaults: { _controller: MultiServiceGsmPiecesBundle:Default:index }

multi_service_gsm_pieces_affiche:
    path:  /piece/affiche 
    defaults: { _controller: MultiServiceGsmPiecesBundle:Piece:piece}