
multi_service_gsm_front_homepage:
    path:     /front
    defaults: { _controller: MultiServiceGsmFrontBundle:Default:index }

multi_service_gsm_front_admin:
   resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/admin.yml"
   prefix:   /admin

multi_service_gsm_front_Reparation:
    resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/reparation.yml"
    prefix:   /admin/reparation

multi_service_gsm_front_tarif:
   resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/tarif.yml"
   prefix:   /admin/tarif

multi_service_gsm_front_modele:
        resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/modele.yml"
        prefix:   /admin/modele

multi_service_gsm_front_marque:
        resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/marque.yml"
        prefix:   /admin/marque

multi_service_gsm_front_info:
        path: /info
        defaults: { _controller: MultiServiceGsmFrontBundle:Default:inf }

multi_service_gsm_front_appl:
        path: /{id}/modelapp
        defaults: { _controller: MultiServiceGsmFrontBundle:Appl:app }

multi_service_gsm_front_model_reparation:
        path: /{id}/modelrep
        defaults: { _controller: MultiServiceGsmFrontBundle:RepaModel:rep }


multi_service_gsm_front_devis:
        path: /{id}/devis
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:dev }
multi_service_gsm_front_devis_marque:
        path: /allMarque
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:marqueAjax}
multi_service_gsm_front_devis_modele:
        path: /modele/{slug}
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:modeleAjax}
multi_service_gsm_front_devis_reparation:
        path: /{slug}/reparation
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:reparationAjax}

multi_service_gsm_front_formDevis:
        path: /formulaire_devis
        defaults: {_controller: MultiServiceGsmFrontBundle:Default:dev}