
multi_service_gsm_front_homepage:
    path:     /front
    defaults: { _controller: MultiServiceGsmFrontBundle:Default:index }

multi_service_gsm_front_admin:
   resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/admin.yml"
   prefix:   /admin

multi_service_gsm_front_Reparation:
    resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/reparation.yml"
    prefix:   /admin/reparation

multi_service_gsm_front_tarif:
   resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/tarif.yml"
   prefix:   /admin/tarif

multi_service_gsm_front_modele:
        resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/modele.yml"
        prefix:   /admin/modele

multi_service_gsm_front_marque:
        resource: "@MultiServiceGsmFrontBundle/Resources/config/routing/marque.yml"
        prefix:   /admin/marque


multi_service_gsm_front_info:
        path: /info
        defaults: { _controller: MultiServiceGsmFrontBundle:Default:inf }

multi_service_gsm_front_localisation:
    path: /localisation
    defaults: { _controller: MultiServiceGsmFrontBundle:Default:localisation}


multi_service_gsm_front_appl:
        path: /{slug}/modelapp
        defaults: { _controller: MultiServiceGsmFrontBundle:Appl:app }

multi_service_gsm_front_model_reparation:
        path: /{marque}/{modele}/modelrep
        defaults: { _controller: MultiServiceGsmFrontBundle:RepaModel:rep }

multi_service_gsm_front_fiche_reparation:
        path: /{marque}/{modele}/{reparation}
        defaults: { _controller: MultiServiceGsmFrontBundle:FicheReparation:fiche}





multi_service_gsm_front_devis:
        path: /{id}/devis
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:dev }

multi_service_gsm_front_devis_marque:
        path: /allMarque
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:marqueAjax}
multi_service_gsm_front_devis_modele:
        path: /modele/{slug}
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:modeleAjax}
multi_service_gsm_front_devis_reparation:
        path: /{slug}/reparation
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:reparationAjax}
multi_service_gsm_front_devis_prix_reparation:
        path: /prixreparation
        defaults: { _controller: MultiServiceGsmFrontBundle:Devis:affichprix}





multi_service_gsm_front_formDevis:
        path: /formulaire_devis
        defaults: {_controller: MultiServiceGsmFrontBundle:Default:dev}

multi_service_gsm_front_marques:
        path: /marques
        defaults: { _controller: MultiServiceGsmFrontBundle:Default:marq}


multi_service_gsm_front_adresse:
    path: /adressepostale
    defaults: { _controller: MultiServiceGsmFrontBundle:Adresse:add }
    methods:  [GET, POST]

multi_service_gsm_front_panier:
    path: /panier
    defaults: { _controller: MultiServiceGsmFrontBundle:Panier:panier}

multi_service_gsm_front_recapitulatif:
    path: /panier/recapitulatif
    defaults: { _controller: MultiServiceGsmFrontBundle:Panier:recapitulatif }

multi_service_gsm_front_validation:
    path: /panier/validation
    defaults: { _controller: MultiServiceGsmFrontBundle:Panier:validation }

multi_service_gsm_front_ajouter:
    path: /ajouter/{id}
    defaults: { _controller: MultiServiceGsmFrontBundle:Panier:ajout }

multi_service_gsm_front_suppression:
    path: /supprimer/{id}
    defaults: { _controller: MultiServiceGsmFrontBundle:Panier:supprim}