multi_service_gsm_user:
    resource: "@MultiServiceGsmUserBundle/Resources/config/routing.yml"
    prefix:   /

multi_service_gsm_front:
    resource: "@MultiServiceGsmFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

multi_service_gsm_login:
   path: /login
   defaults:
    _controller: MultiServiceGsmUserBundle:Security:login

multi_service_gsm_login_check:
  path: /login_check

multi_service_gsm_logout:
  path: /logout

