multi_service_gsm_user_homepage:
    path:     /
    defaults: { _controller: MultiServiceGsmUserBundle:Default:index }

multi_service_gsm_user_delete:
    path: /deleteUser/{id}
    defaults: { _controller: MultiServiceGsmUserBundle:Default:deleteUser }
    requirements:
      id: \d+
multi_service_gsm_user_adresse:
    path: /profil/adressepostale/add
    defaults: { _controller: MultiServiceGsmUserBundle:Adresse:add }
app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"